const bookingURL='https://calendar.app.google/7RqCZp1X4w5JTaJ4A';
const screens={hero:document.getElementById('hero'),flow:document.getElementById('flow'),loading:document.getElementById('loading'),result:document.getElementById('result')};
const steps=[...document.querySelectorAll('.step')];let current=0;const labels=['BUSINESS SNAPSHOT','BUSINESS MODEL','DEMAND SOURCES','ENQUIRY HANDLING','QUOTE & SALES','GROWTH GOALS'];
const show=s=>{Object.values(screens).forEach(x=>x.classList.remove('active'));screens[s].classList.add('active');scrollTo(0,0)};
document.getElementById('beginBtn').onclick=()=>show('flow');
const stepNum=document.getElementById('stepNum'),stepLabel=document.getElementById('stepLabel'),nextBtn=document.getElementById('nextBtn'),backBtn=document.getElementById('backBtn');
function renderStep(){steps.forEach((s,i)=>s.classList.toggle('active',i===current));stepNum.textContent=String(current+1).padStart(2,'0');stepLabel.textContent=labels[current];backBtn.style.visibility=current?'visible':'hidden';nextBtn.textContent=current===steps.length-1?'Generate score':'Continue';}
function validate(){const active=steps[current];let ok=true;active.querySelectorAll('[required]').forEach(el=>{if(!el.value.trim()){el.classList.add('invalid');ok=false}else el.classList.remove('invalid')}); if(active.querySelector('.chips')){const on=active.querySelectorAll('.chips .on'); if(!on.length){active.querySelector('.chips').classList.add('shake'); ok=false}else active.querySelector('.chips').classList.remove('shake')} return ok;}
document.querySelectorAll('.chips button').forEach(b=>b.onclick=e=>{e.preventDefault();b.classList.toggle('on')});
backBtn.onclick=()=>{if(current>0){current--;renderStep();scrollTo(0,0)}};
nextBtn.onclick=async()=>{if(!validate())return;if(current<steps.length-1){current++;renderStep();scrollTo(0,0)}else await finish();};
renderStep();
function fd(){const form=document.getElementById('diagnosisForm');const selected=[...document.querySelectorAll('.chips .on')].map(x=>x.textContent).join(', ');document.getElementById('leadSourcesInput').value=selected;const d=Object.fromEntries(new FormData(form).entries());d.leadSources=selected;return d}
function score(d){let s=70; if(['When there is time','Inconsistent'].includes(d.replySpeed))s-=14; if(['Often','Sometimes'].includes(d.missedCalls))s-=10; if(['Usually nothing','One follow-up sometimes'].includes(d.quoteFollowup))s-=12; if(!d.leadSources.includes('Google')&&!d.leadSources.includes('Paid ads'))s-=8; if(['0–5','6–15'].includes(d.jobs))s-=4; return Math.max(35,Math.min(86,s));}
function buildMetrics(base){return [['Lead Generation',base-6],['Sales & Conversion',base-2],['Offers & Positioning',base-9],['Operations & Systems',base+5],['Marketing & Visibility',base+1],['Customer Journey',base-5],['Profit & Pricing',base+7]].map(([n,v])=>[n,Math.max(30,Math.min(88,v))]);}
function renderResults(sc){document.getElementById('scoreNum').textContent=sc;const m=buildMetrics(sc);document.getElementById('metrics').innerHTML=m.map(([n,v])=>`<div class="metric"><span>${n}</span><div class="bar"><i style="width:${v}%"></i></div><b>${v}<small>/100</small></b></div>`).join('');document.getElementById('bookingLink').href=bookingURL;}
async function submitNetlify(d,sc){const form=document.getElementById('diagnosisForm');const summary=`Score ${sc}/100. Lead sources: ${d.leadSources}. Bottleneck: ${d.bottleneck}. Recommended first move: tighten client journey before adding more demand. Booking link shown: ${bookingURL}`;document.getElementById('scoreInput').value=sc;document.getElementById('summaryInput').value=summary;const params=new URLSearchParams(new FormData(form));params.set('form-name','arena-business-diagnosis');params.set('score',sc);params.set('summary',summary);try{await fetch('/',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:params.toString()})}catch(e){console.warn(e)}}
async function finish(){const d=fd();const sc=score(d);renderResults(sc);show('loading');await submitNetlify(d,sc);setTimeout(()=>show('result'),2600)}
